### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by games647** [vik1395/BungeeAuth-Minecraft#1]
I've seen that you are back. Do you have any plans on providing a maven repository for this project? I want to use this project as dependency. 

BTW: I have a lot users you actually liked this project and asked for continuation.

**Comment by vik1395** [comment]
I have just started working on setting up a maven repository, Ill link it once its ready. 

I am slowly working my way through updating my plugins, and Ill definitely update this one :)

**Comment by games647** [comment]
Cool thanks man

**Comment by vik1395** [comment]
I just uploaded it to repo.vik1395.me. You can check out the path at https://github.com/vik1395/repo.vik1395.me
