### ISSUE TITLE
Fallbacks servers are broken

### ISSUE THREAD

**Issue by xion87** [vik1395/BungeeAuth-Minecraft#2]
**Fallback Lobby** and **Fallback AuthLobby** never worked for me and do nothing (if lobby is down it must teleport the user at fallback lobby right?)

**Comment by vik1395** [comment]
You should add the fallback servers to the priorities field in BungeeCord's config.yml. Otherwise it won't work.

For more info: https://www.spigotmc.org/wiki/bungeecord-configuration-guide/
