### ISSUE TITLE
Problem with FastLogin

### ISSUE THREAD

**Issue by NotDemonix** [vik1395/BungeeAuth-Minecraft#33]
Hey, soo i tried adding fastlogin and it doesnt autologin (people still have to use /login) and also i dont have 2 servers for lobby (auth one and main lobby) so i have to use the same server

**Comment by NathanAdhitya** [comment]
I have a fork that addressed this issue for my own use. Perhaps consider checking out my fork. Let me know if you need help compiling.
https://github.com/NathanAdhitya/BungeeAuth-Minecraft

**Comment by NotDemonix** [comment]
> I have a fork that addressed this issue for my own use. Perhaps consider checking out my fork. Let me know if you need help compiling. https://github.com/NathanAdhitya/BungeeAuth-Minecraft

yk it got fixed?
