### ISSUE TITLE
Rare warn

### ISSUE THREAD

**Issue by xion87** [vik1395/BungeeAuth-Minecraft#4]
I find this small warn dunno what is:  http://hastebin.com/urarigewup.lua

**Comment by vik1395** [comment]
This isn't really a bug. Just happens when player logs in just as he is about to get kicked for taking too long. You can ignore the error.

**Comment by xion87** [comment]
Can you explain why the file is 4 mb now?...

**Comment by vik1395** [comment]
It has SQLite packaged into it for those who want to use an SQLite database instead of MySQL
