### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by xion87** [vik1395/BungeeAuth-Minecraft#5]
these two strings **reset_noreg** and **reset_success** in messages %player% string will be alway the player that typed the command **/reset** instead the target player

**Comment by vik1395** [comment]
I'll be fixing this in the next update, thanks for reporting it.

**Comment by vik1395** [comment]
This issue was fixed in https://github.com/vik1395/BungeeAuth-Minecraft/commit/2648ff4273c51caf46433452258fb7369890de54

You can download the latest version here to test it out: https://github.com/vik1395/BungeeAuth-Minecraft/raw/master/target/BungeeAuth-1.4.jar
