### ISSUE TITLE
API for ForceAction

### ISSUE THREAD

**Issue by games647** [vik1395/BungeeAuth-Minecraft#6]
Since you are back, we could also submit feature right? 

It would be a lot easier for my project FastLogin if you add an API for force actions like forceLogin(ProxiedPlayer), forceRegister(ProxiedPlayer) and isRegistered(playerName). I'm currently using reflection, but this leads to a really bad coding style and could be error-prone (especially if a security manager is activated). 

Current hook of mine: https://github.com/games647/FastLogin/blob/master/bungee/src/main/java/com/github/games647/fastlogin/bungee/hooks/BungeeAuthHook.java

I didn't necessary mean that you need to hook into FastLogin. I just mean to add an API that maybe other plugins could also use.

**Comment by vik1395** [comment]
Thanks for the suggestion, I'm working on getting them setup in the next update.

**Comment by vik1395** [comment]
The features you had suggested have been added in https://github.com/vik1395/BungeeAuth-Minecraft/commit/84b2c665f2f4f46679481a605f9c1ab45bf14a8b

You can check it out at https://github.com/vik1395/BungeeAuth-Minecraft/blob/master/src/me/vik1395/BungeeAuthAPI/RequestHandler.java

**Comment by games647** [comment]
Where is the forceLogin method?

**Comment by vik1395** [comment]
I have added it in the latest commit https://github.com/vik1395/BungeeAuth-Minecraft/commit/1c6ca4f020292cbca131d729a7c961781c76f2c3

The API page has also been updated

**Comment by games647** [comment]
Do you have any plans when you are going to release it?

**Comment by vik1395** [comment]
I'm just testing it out to see for any errors, should be released this evening or tomorrow

**Comment by games647** [comment]
Could you upload the the new version to the repository too?

**Comment by vik1395** [comment]
Sorry, though I had uploaded it already. It's done now

**Comment by games647** [comment]
How should we access the method, because they aren't static. Should we create a new RequestHandler on our own?

**Comment by vik1395** [comment]
Hmm my original plan was to have developers create a new RequestHandler, but I think I'll change the methods to static, it makes more sense.
