### ISSUE TITLE
Suggestion: kick on wrong password

### ISSUE THREAD

**Issue by xion87** [vik1395/BungeeAuth-Minecraft#7]
I would suggest to add kick from the bungee when fail to type password, it will prevent brute force attack with login command spam.

**config.yml**
`Kick on Wrong Password: true`

**messages.yml**
`wrongpass_kick: "Wrong password!"`

**Comment by vik1395** [comment]
Thanks for the suggestion, I'm working on implementing this in the next update

**Comment by vik1395** [comment]
This feature has been added in https://github.com/vik1395/BungeeAuth-Minecraft/commit/84b2c665f2f4f46679481a605f9c1ab45bf14a8b

You can get this version of the plugin at https://github.com/vik1395/BungeeAuth-Minecraft/raw/master/target/BungeeAuth-1.4.jar

Please reset your messages.yml and config.yml for the new variables to show up. If too many wrong password attempts are made, the player is put in a time out where their /login commands won't do anything.
